---
- name: "daemon reload"
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: "daemon reload"

- name: "service restart"
  ansible.builtin.systemd_service:
    name: "{{ service_restart_name }}"
    state: "{{ systemd_unit_CanReload | bool | ansible.builtin.ternary('reloaded','restarted') }}"
  listen: "service restart"
