---

- name: "{{ service_obj.name }} :: Read systemd config"
  ansible.builtin.shell: |
    systemctl show -P CanReload {{ service_obj.name }}
  changed_when: false
  register: systemd_unit_CanReload

- name: "{{ service_obj.name }} :: Prepare configs"
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('644') }}"
    backup: "{{ item.backup | default('false') }}"
    content: "{{ item.content }}"
  loop: "{{ service_obj.configs }}"
  notify: "service restart"
