---

- name: "{{ service_obj.name }} :: Read systemd config"
  shell: |
    systemctl show -P CanReload {{ service_obj.name }}
  register: systemd_unit_CanReload | bool

- name: "{{ service_obj.name }} :: Prepare configs"
  copy:
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('644') }}"
    backup: "{{ item.backup | default('false') }}"
    content: "{{ item.content }}"
  loop: "{{ service_obj.configs }}"
  notify: "service restart"
