---
- name: "{{ service_obj.name }} :: Perform pre-shell command"
  shell: "{{ item }}"
  loop: "{{ service_obj.init.pre_shell_commands }}"
  when: service_obj.init.pre_shell_commands is defined

