---
- block:
    - name: "{{ service_obj.name }} - Init Pre"
      ansible.builtin.include_tasks: init_pre.yml
      when:
        - ansible_call.init | bool
        - ansible_call.name == service_obj.name

    - name: "{{ service_obj.name }} - Config"
      ansible.builtin.include_tasks: config.yml

    - name: "{{ service_obj.name }} - Systemd"
      ansible.builtin.include_tasks: systemd.yml

    - name: "{{ service_obj.name }} - Init Post"
      ansible.builtin.include_tasks: init_post.yml
      when:
        - ansible_call.init | bool
        - ansible_call.name == service_obj.name
  when:
    - not full_init | bool

- block:
    - name: "{{ service_obj.name }} - Init Pre"
      ansible.builtin.include_tasks: init_pre.yml

    - name: "{{ service_obj.name }} - Config"
      ansible.builtin.include_tasks: config.yml

    - name: "{{ service_obj.name }} - Systemd"
      ansible.builtin.include_tasks: systemd.yml

    - name: "{{ service_obj.name }} - Init Post"
      ansible.builtin.include_tasks: init_post.yml
  when:
    - full_init | bool
